changes column type to uuid
NCCE/teachcomputing.org pull request #1640
Opened 2023-01-11 16:31 UTC by nyashamaphosa

## Status

* Current Status:Ready for review
* Closes https://github.com/NCCE/teachcomputing.org-issues/issues/2137

## What's changed?

*Switch column type to uuid*

2023-01-24 14:59 UTC, danhalson commented on spec/jobs/achiever/update_users_details_from_achiever_job_spec.rb
> -  let(:user) { create(:user, stem_achiever_contact_no: 'contact-valid') }
I think these tests are still valuable, as they off coverage that the validations are working correctly - if you change `contact-valid` to a valid uuid, they should pass?

2023-01-24 15:02 UTC, danhalson commented on spec/models/user_spec.rb
> +  let(:user) { create(:user, stem_user_id: "id-stem_user", email: 'user@example.com')}
the idea of this test was the check OmniAuth was doing the correct thing with the data, by using the user factory instead we've lost that coverage, as with the test above, I think that using a proper uuid for the `achiever_contact_no` will fix whatever errors you were seeing

2023-01-24 15:07 UTC, danhalson requested changes
Now the test envvars have been fixed the main issue you were seeing should be sorted, then if you do the following you should get passes:

* Point `stub_valid_contact_details` back to `https://stemraspberrypiapi.dev3.smartmembership.net`
* Reinstate the removed test steps & test data
* Update test data in the specs to use a proper uuid for `stem_achiever_contact_no`

2023-02-17 10:14 UTC, danhalson approved these changes
Approving the non me parts of this

2023-02-20 10:08 UTC, grega approved these changes

2023-03-02 08:44 UTC, merged